services:
  app:
    build: .
    container_name: conference_app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: conference_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conference_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
